apiVersion: fleet.cattle.io/v1alpha1
kind: HelmOp
metadata:
  name: arr-stack
  namespace: fleet-local
spec:
  helm:
    pollingInterval: 1m
    repo: oci://harbor.ryzen.me/library/arr-stack
    version: 0.3.0
    values:
      ingress:
        domain: media.ryzen.me
      qbittorrent:
        persistent:
          size: 1Ti
          storageClass: media
        vpn:
          secret:
            existing: true
            name: arr-config-secret
            privateKeySecretKey: WIREGUARD_PRIVATE_KEY
            addressesSecretKey: WIREGUARD_ADDRESSES
        extraEnv:
          - name: MAM_ID
            valueFrom:
              secretKeyRef:
                name: media-mam-secret
                key: mam_id
        lifecycle:
          postStart:
            exec:
              command:
                - "/bin/sh"
                - "-c"
                - |
                  CONFIG_FILE="/config/qBittorrent/qBittorrent.conf"
                  echo "Waiting for $CONFIG_FILE to exist..."
                  for i in $(seq 1 40); do
                    if [ -f "$CONFIG_FILE" ]; then
                      break
                    fi
                    sleep 0.5
                  done
                  echo "Config found. Patching WebUI\LocalHostAuth..."
                  # If setting exists, replace it; otherwise append after [Preferences]
                  if grep -Fq "WebUI\LocalHostAuth=" "$CONFIG_FILE"; then
                    sed -i 's|WebUI\\LocalHostAuth=.*|WebUI\\LocalHostAuth=false|' "$CONFIG_FILE"
                  else
                    sed -i '/^\[Preferences\]/a WebUI\\LocalHostAuth=false' "$CONFIG_FILE"
                  fi

                  echo "Setting MAM ip"
                  curl -c ~/mam.cookies -b "mam_id=$MAM_ID" https://t.myanonamouse.net/json/dynamicSeedbox.php
      arr:
        persistent:
          size: 2Ti
          storageClass: media
        config:
          storageClass: retain
      metrics:
        enabled: true
        podAnnotations:
          signoz.io/path: /metrics
          signoz.io/port: '7100'
          signoz.io/scrape: 'true'
      discord:
        enabled: true
        secret:
          existing: true
          name: arr-config-secret
  defaultNamespace: media